version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lambda-fastapi-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: lambda_fastapi_db
    volumes:
      - lambda_fastapi_data:/var/lib/postgresql/data

volumes:
  lambda_fastapi_data: